CREATE TABLE IF NOT EXISTS api_audit_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    request_ts BIGINT NOT NULL,
    response_ts BIGINT NOT NULL,
    duration_ms INT NOT NULL,
    method VARCHAR(16) NOT NULL,
    path VARCHAR(255) NOT NULL,
    query_string TEXT NULL,
    status_code SMALLINT NOT NULL,
    client_ip VARCHAR(64) NULL,
    user_agent VARCHAR(512) NULL,
    api_key VARCHAR(255) NULL,
    request_content_type VARCHAR(255) NULL,
    response_content_type VARCHAR(255) NULL,
    request_headers_json MEDIUMTEXT NULL,
    response_headers_json MEDIUMTEXT NULL,
    request_body MEDIUMTEXT NULL,
    response_body MEDIUMTEXT NULL,
    request_body_size INT NOT NULL DEFAULT 0,
    response_body_size INT NOT NULL DEFAULT 0,
    request_body_truncated TINYINT(1) NOT NULL DEFAULT 0,
    response_body_truncated TINYINT(1) NOT NULL DEFAULT 0,
    uuid VARCHAR(64) NULL,
    task_id VARCHAR(64) NULL,
    task_type VARCHAR(128) NULL,
    bid VARCHAR(128) NULL,
    error_code VARCHAR(128) NULL,
    created_ts BIGINT NOT NULL,
    PRIMARY KEY (id),
    KEY idx_request_ts (request_ts),
    KEY idx_path_request_ts (path, request_ts),
    KEY idx_status_request_ts (status_code, request_ts),
    KEY idx_api_key_request_ts (api_key, request_ts),
    KEY idx_task_id (task_id),
    KEY idx_uuid (uuid),
    KEY idx_task_type_request_ts (task_type, request_ts),
    KEY idx_bid (bid),
    KEY idx_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tg_bid_watch (
    bid VARCHAR(128) NOT NULL,
    note VARCHAR(255) NULL,
    created_ts BIGINT NOT NULL,
    PRIMARY KEY (bid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
